### ISSUE TITLE
Only works with dataloader and batch size of 1

### ISSUE THREAD

**Issue by giblets2570** [jas-preet/SPOT-1D-Single#1]
Increasing the batch size for the dataloader raises:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tom/miniconda3/envs/ordaos/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/Network.py", line 49, in forward
    _20 = [hx, hx]
    _21 = [_13, _9, _5, _1, _14, _10, _6, _2, _15, _11, _7, _3, _16, _12, _8, _4]
    _22, _23, _24 = torch.lstm(input0, batch_sizes, _20, _21, True, 2, 0.5, False, True)
                    ~~~~~~~~~~ <--- HERE
    max_seq_length = ops.prim.NumToTensor(torch.size(batch_sizes, 0))
    input1, _25 = torch._pad_packed_sequence(_22, batch_sizes, True, 0, int(max_seq_length))

Traceback of TorchScript, original code (most recent call last):
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/rnn.py(529): forward_impl
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/rnn.py(554): forward_packed
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/rnn.py(562): forward
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/module.py(539): __call__
/home/jaspreet/jaspreet_data/results/lstm2layer_run_final/model.py(34): forward
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/module.py(525): _slow_forward
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/nn/modules/module.py(539): __call__
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/jit/__init__.py(997): trace_module
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/torch/jit/__init__.py(858): trace
/tmp/pycharm_project_529/test_serving.py(66): <module>
/home/jaspreet/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py(18): execfile
/home/jaspreet/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py(197): runfile
<ipython-input-2-6bc706fa173e>(1): <module>
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3331): run_code
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3254): run_ast_nodes
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3063): run_cell_async
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/async_helpers.py(68): _pseudo_sync_runner
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2886): _run_cell
/home/jaspreet/anaconda3/envs/pytorch_env1/lib/python3.7/site-packages/IPython/core/interactiveshell.py(2858): run_cell
/home/jaspreet/.pycharm_helpers/pydev/_pydev_bundle/pydev_ipython_console_011.py(483): add_exec
/home/jaspreet/.pycharm_helpers/pydev/_pydev_bundle/pydev_ipython_console.py(36): do_add_exec
/home/jaspreet/.pycharm_helpers/pydev/_pydev_bundle/pydev_code_executor.py(106): add_exec
/home/jaspreet/.pycharm_helpers/pydev/pydevconsole.py(258): process_exec_queue
/home/jaspreet/.pycharm_helpers/pydev/pydevconsole.py(381): start_server
/home/jaspreet/.pycharm_helpers/pydev/pydevconsole.py(485): <module>
RuntimeError: Expected cell size [4, 2, 1000], got [4, 1, 1000]```

**Comment by jas-preet** [comment]
HI,
Thanks for using the predictor. This error has been an open issue with exporting models using Jit Trace. please refer to this thread to gain further insight. https://github.com/pytorch/pytorch/issues/15319

**Comment by giblets2570** [comment]
@jas-preet Hi, thanks for the reply, and thanks for the predictor. Is there a non-jit exported model I could use instead?

**Comment by jas-preet** [comment]
Unfortunately at this stage, due to limited resources and scarce time, we are not looking to update anything in terms of this project but to support the smooth operation of already available methods. Apologies for any inconvenience caused to you.
